ALTER TABLE test1 rt_mem_limit='1G'
ALTER TABLE test1 rt_mem_limit='1G'
select * from test1
ALTER TABLE test1 rt_mem_limit='1G'
ALTER TABLE test1 rt_mem_limit='1G'
select * from test1
ALTER TABLE test1 rt_mem_limit='1G'
ALTER TABLE test1 rt_mem_limit='1G'
select * from test1
ALTER TABLE test1 rt_mem_limit='1G'
ALTER TABLE test1 rt_mem_limit='1G'
select * from test1
ALTER TABLE test1 rt_mem_limit='1G'
ALTER TABLE test1 rt_mem_limit='1G'
select * from test1
ALTER TABLE test1 rt_mem_limit='1G'
ALTER TABLE test1 rt_mem_limit='1G'
select * from test1
ALTER TABLE test1 rt_mem_limit='1G'
ALTER TABLE test1 rt_mem_limit='1G'
select * from test1
ALTER TABLE test1 rt_mem_limit='1G'
ALTER TABLE test1 rt_mem_limit='1G'
select * from test1
ALTER TABLE test1 rt_mem_limit='1G'
ALTER TABLE test1 rt_mem_limit='1G'
select * from test1
ALTER TABLE test1 rt_mem_limit='1G'
ALTER TABLE test1 rt_mem_limit='1G'
select * from test1