create table test1 ( title text, tag integer );
insert into test1 values (1, 'word form', 11);
flush ramchunk test1;
insert into test1 values (2, 'word form', 11);
flush ramchunk test1;
insert into test1 values (3, 'word form', 11);
flush ramchunk test1;
insert into test1 values (4, 'word form', 11);
flush ramchunk test1;
insert into test1 values (5, 'word form', 11);
flush ramchunk test1;
insert into test1 values (6, 'word form', 11);
flush ramchunk test1;
insert into test1 values (7, 'word form', 11);
flush ramchunk test1;
insert into test1 values (8, 'word form', 11);
flush ramchunk test1;